#!/usr/bin/env python3
"""Maakt korte omschrijvingen uit README's van repos zonder GitHub-omschrijving.

Gebruik:  python3 scripts/summarize_readmes.py pad/naar/pool.json pad/naar/readmes/
Leest <readmes>/<eigenaar>__<repo>.md en schrijft data/readme_summaries.tsv (repo<TAB>omschrijving).
Repos waarvan de README op exploits/cheats wijst, template-README's en lege README's vallen af.
"""
import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_extra import BLOCK, GAME_SCRIPT, ROOT  # noqa: E402

OUT = ROOT / "data" / "readme_summaries.tsv"
BLOCKED_OUT = ROOT / "data" / "readme_blocked.txt"

# Sterke exploit-signalen in de README zelf (code of instructies), los van het woordfilter
README_BLOCK = re.compile(
    r"loadstring\s*\(|game:httpget|getgenv\s*\(|hookmetamethod|hookfunction|syn\.request|firetouchinterest|"
    r"fireclickdetector|setclipboard|\bexecutors?\b|\binject(or|ed|ing)?\b|exploit you|your exploit|\bcheats?\b|"
    r"aimbot|keyless|key ?system|script ?hub|auto ?-?farm|\bbypass|cookie|stealer|robux|pastebin\.com|"
    r"discord\.gg/|\.rar\b|virustotal|antivirus|disable (your )?(windows )?defender|educational purposes|"
    r"\bleak(s|ed)?\b|captcha|\bbot accounts?|account ?generat|g[ée]n[ée]rat(eur|or) de comptes|join ?logger|"
    r"paid (plugins?|models?|assets?)\W.{0,30}free|internal base|\bnitro\b|robloxsecurity|\.roblosecurity|"
    r"fflags?\b|fast[- _]?flags?|clientappsettings|client[- _]?optimi|\bmacros?\b|pyautogui|keyboard (and mouse )?actions|"
    r"mouse and keyboard actions|free (robux|premium|items)",
    re.I,
)
# Standaard-README's van templates (rojo init, create-react-app, ...) zeggen niets over het project
TEMPLATE = re.compile(
    r"generated by \[?rojo|to build the place from scratch|this project was bootstrapped|getting started with create|"
    r"^welcome to your|edit this readme|add your files|replace this|lorem ipsum",
    re.I | re.M,
)


# Alinea's die instructies of credits zijn in plaats van een omschrijving
SKIP_PARA = re.compile(
    r"(?i)(table of contents|contents|install|usage|license|credits?\b|requirements|to (use|install|run|get started)|"
    r"run |use the |clone |download|open |go to |step \d|support:|if you|please|note:|disclaimer|warning|"
    r"the complete credit|made by|this is made for|thanks? |special thanks|copyright|all rights reserved|"
    r"this (library|package|plugin|module) (works|requires|is only)|you (need|must|will need))"
)


def strip_markdown(text):
    text = re.sub(r"(?s)<!--.*?-->", " ", text)
    text = re.sub(r"(?s)```.*?```", " ", text)
    text = re.sub(r"(?s)<(script|style)\b.*?</\1>", " ", text, flags=re.I)
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", text)          # afbeeldingen/badges
    text = re.sub(r"\[!\[[^\]]*\]\([^)]*\)\]\([^)]*\)", " ", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)        # links -> tekst
    text = re.sub(r"<[^>]+>", " ", text)                        # html-tags
    text = re.sub(r"https?://\S+", " ", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"[*_~]{1,3}([^*_~\n]+)[*_~]{1,3}", r"\1", text)
    text = text.replace("&nbsp;", " ").replace("&amp;", "&")
    return text


def summarize(raw):
    """(titel, eerste inhoudelijke alinea) uit een README."""
    text = strip_markdown(raw)
    title = ""
    m = re.search(r"^\s*#{1,3}\s*(.+)$", text, re.M)
    if m:
        title = m.group(1).strip(" #")
    paras = re.split(r"\n\s*\n", text)
    for p in paras:
        lines = [ln.strip() for ln in p.strip().splitlines()]
        lines = [ln for ln in lines if ln and not re.match(r"^(#|\||-{3,}|={3,}|>\s*\[!)", ln)]
        if not lines:
            continue
        s = " ".join(re.sub(r"^([-*+]|\d+[.)])\s+", "", ln) for ln in lines)
        s = re.sub(r"\s+", " ", s).strip(" >")
        words = re.findall(r"[^\W\d_]{2,}", s)
        if len(words) < 6 or len(s) < 40:
            continue
        if sum(ch.isalpha() for ch in s) < 0.6 * len(s):
            continue
        if SKIP_PARA.match(s):
            continue
        if len(s) > 220:
            cut = s[:220]
            end = max(cut.rfind(". "), cut.rfind("! "), cut.rfind("? "))
            s = cut[: end + 1] if end > 80 else cut.rsplit(" ", 1)[0] + " …"
        return title, s
    return title, ""


def main(pool_path, readme_dir):
    pool = json.load(open(pool_path, encoding="utf-8"))
    readme_dir = Path(readme_dir)
    found, blocked = {}, []
    reasons = Counter()
    heads = Counter()
    for f in readme_dir.glob("*.md"):
        key = f.stem.replace("__", "/", 1)
        if key not in pool:
            continue
        raw = f.read_bytes()[:60000].decode("utf-8", "replace")
        if len(raw.strip()) < 60:
            reasons["lege README"] += 1
            continue
        head = f"{key.split('/')[1]} {raw[:4000]}"
        if README_BLOCK.search(head):
            reasons["exploit/cheat in README"] += 1
            blocked.append(pool[key]["repo"])
            continue
        if TEMPLATE.search(head):
            reasons["template-README"] += 1
            continue
        title, summary = summarize(raw)
        if not summary:
            reasons["geen inhoudelijke alinea"] += 1
            continue
        if BLOCK.search(f"{title} {summary}") or GAME_SCRIPT.search(f"{title} {summary}"):
            reasons["exploit/cheat/spam"] += 1
            blocked.append(pool[key]["repo"])
            continue
        norm = re.sub(r"\d+", "0", summary.lower())
        heads[norm] += 1
        found[key] = (pool[key]["repo"], summary, norm)
    rows = []
    for key, (repo, summary, norm) in found.items():
        if heads[norm] >= 3:  # zelfde alinea in 3+ repos = template of kopie
            reasons["zelfde tekst als andere repos"] += 1
            continue
        rows.append((repo, summary.replace("\t", " ")))
    rows.sort(key=lambda r: r[0].lower())
    with OUT.open("w", encoding="utf-8") as f:
        f.write("repo\tsummary\n")
        for repo, summary in rows:
            f.write(f"{repo}\t{summary}\n")
    BLOCKED_OUT.write_text("".join(f"{r}\n" for r in sorted(blocked, key=str.lower)), encoding="utf-8")
    print(f"{len(blocked)} repos met exploit/cheat-README naar {BLOCKED_OUT.relative_to(ROOT)}")
    print(f"{len(rows)} omschrijvingen naar {OUT.relative_to(ROOT)}")
    for k, v in reasons.most_common():
        print(f"  overgeslagen ({k}): {v}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
